version: '3.4'
services:
    goerli-parity.dnp.dappnode.eth:
        image: 'goerli-parity.dnp.dappnode.eth:0.0.1'
        build: ./build
        volumes:
            - 'goerli:/goerli'
        environment: 
            - EXTRA_OPTS=
        ports:
            - '127.0.0.1:8546:8546'
            - '127.0.0.1:8545:8545'
            - '54535:30303'
            - '54535:30303/udp'
            - '54534:30304/udp'
volumes:
    goerli: {}
